baseURL = "https://jovmit.io"
languageCode = "en-us"
title = "Jovche Mitrejchevski"
theme = "ananke"
googleAnalytics = "UA-148368240-1"
disqusShortname = "jovmit"

[taxonomies]
  tag = "tags"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/jovche/jovche.png"
  description = "Welcome to TDD on Android Academy"
  twitter = "https://twitter.com/jovchem"
  github = "https://github.com/mitrejcevski"
  youtube = "https://www.youtube.com/channel/UC71omjio31Esx7LytaZ2ytA"
  medium = "https://medium.com/@jovmit"
  linkedin = "https://www.linkedin.com/in/jovmit/"
  instagram = "https://www.instagram.com/jovchem/"
  background_color_class = "bg-black"
  featured_image = "/images/theme/side_background.jpg"
  recent_posts_number = 5
  show_reading_time = true
  custom_css = ["css/custom.css", "css/typography.css"]

[menu]

[[menu.main]]
  identifier = "blog"
  name = "Posts"
  title = "Blog section"
  url = "/posts/"

[[menu.main]]
    identifier = "about"
    name = "About"
    title = "About section"
    url = "/about/"

[[menu.main]]
  identifier = "tips"
  name = "Tips"
  title = "Tips and tricks section"
  url = "/tips/"
